### ISSUE TITLE
Check if we use the correct imprint

### ISSUE THREAD

**Issue by Baschdl** [KDD-OpenSource/32de-UI#16]
Check if we use the correct imprint or if we need one like [https://we.analyzegenomes.com/imprint/](https://we.analyzegenomes.com/imprint/).

**Comment by juliusrueckin** [comment]
I think, this has already been clarified with the administrators. Thank's for all the phone calls, @Baschdl  :)

**Comment by Baschdl** [comment]
They didn't really give their okay, but at least didn't complain
