### ISSUE TITLE
Fix CORS problem when running system on watson

### ISSUE THREAD

**Issue by Baschdl** [KDD-OpenSource/32de-UI#21]
![untitled](https://user-images.githubusercontent.com/3034832/36264338-c343753e-126c-11e8-84d9-1d3300f33dc2.png)

**Comment by Baschdl** [comment]
I receive the error
![untitled](https://user-images.githubusercontent.com/3034832/36542297-b99ca400-17e0-11e8-98c3-e95b62aebd46.png)
 when running branch `32de-UI/fix-address-server` and `32de-python/deployment-production` on watson.

The error is gone when I insert the following headers.
```javascript
getJsonFromBackend(endpoint, callback) {
      fetch('http://172.20.14.22:8000/' + endpoint, {
          method: 'GET',
          credentials: "include",
          headers: {
              'Access-Control-Allow-Origin': '*',
              'Access-Control-Allow-Methods': 'GET, POST, PATCH, PUT, DELETE, OPTIONS',
              'Access-Control-Allow-Headers': 'Origin, Content-Type, X-Auth-Token'
          },
      }).then((response) => {
        console.log(response);
        return response.json();
      }
      ).then(callback).catch((error) => {
          console.error(error);
      })
      ;
  }
```

But then the website just displays "Loading..." and nothing happens and no request is sent to the server-container. So that's definitely not a fix.

HELP @juliusrueckin @feeds @MkuuWaUjinga

**Comment by Baschdl** [comment]
One possible problem could be http call of our API, this is most probably only allowed on localhost. [https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)

**Comment by Baschdl** [comment]
That was the problem. Switching to https for our API will solve it.

**Comment by GittiHab** [comment]
I have the same issue locally because my UI is running on port `8080` instead of `80`...

**Comment by GittiHab** [comment]
<img width="1281" alt="screen shot 2018-03-08 at 15 28 16" src="https://user-images.githubusercontent.com/6453623/37156100-6763aa7a-22e5-11e8-9116-10986878978d.png">

**Comment by GittiHab** [comment]
If I take out the `CORS(app)` command completely I get a different error, locally

<img width="1288" alt="screen shot 2018-03-08 at 17 31 54" src="https://user-images.githubusercontent.com/6453623/37162917-c969f8c6-22f6-11e8-8f73-85108140e02c.png">

**Comment by GittiHab** [comment]
Maybe the CORS extension doesn't work (as expected)?

**Comment by Baschdl** [comment]
Did you specify the UI port in util/config.py?

**Comment by GittiHab** [comment]
Nope – thanks for pointing that out. #documentation.

**Comment by GittiHab** [comment]
That didn't change anything, though. This is not surprising as it also didn't work when only having `CORS(app)` without any conditional.

**Comment by Baschdl** [comment]
Which UI branch are you using?

**Comment by GittiHab** [comment]
`master` in both cases.

**Comment by Baschdl** [comment]
Using the credentials and agent parameters (https://github.com/KDD-OpenSource/32de-UI/commit/343f9572e9064a1ec320c105b9502c3ce6f7c432) could fix it but I'm not completely sure.

**Comment by GittiHab** [comment]
The weird thing is that when the AJAX-call is made there is **no** CORS-header at all whereas when directly calling the server there is a CORS-header which allows `http://localhost`.

**Comment by Baschdl** [comment]
And the CORS-header is present when accessing our site on watson? There we have `CORS(app, supports_credentials=True, resources={r"/*": {"origins": "*"}})` in the moment. I think I also had some trouble there and went for the quick fix.

**Comment by GittiHab** [comment]
There it works ... maybe we can put the fix in our own repository?

**Comment by juliusrueckin** [comment]
Works again now with customized api endpoint you can specify at build time of our container
