### ISSUE TITLE
Set "homepage" depending on deployment

### ISSUE THREAD

**Issue by Baschdl** [KDD-OpenSource/32de-UI#32]
Set `homepage` depending on where the frontend is deployed
https://github.com/KDD-OpenSource/32de-UI/blob/22c9b9ba8a81bb8188bf03a0a23fe15c992f01cf/pika/package.json#L21

**Comment by juliusrueckin** [comment]
It does not exist a way to set the 'homepage' in our package.json dynamically. Moreover it is not really necessary to define another homepgae than our deployment homepage
