### ISSUE TITLE
After login and logout one gets to result page directly

### ISSUE THREAD

**Issue by MkuuWaUjinga** [KDD-OpenSource/32de-UI#55]
Please fix

**Comment by juliusrueckin** [comment]
... one gets to last active page

**Comment by juliusrueckin** [comment]
Solved issue with commit 351cbc5874dafac0bd0710d3a0eda947399953f2

**Comment by juliusrueckin** [comment]
Solved with commit 518ed37629d8cbc1b830202022dfd56c235f72e8
